# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

pod 'SinchRTC'
pod 'SinchService'

target 'ios-custom-ringtone-calling' do

end

target 'ios-custom-ringtone-callingTests' do

end

